name: 'Push Checkstyle report'
description: 'Push Checkstyle code adherence report'
author: 'Jan-Willem Gmelig Meyling'
inputs:
  path:
    description: 'A file, directory or wildcard pattern that describes where to find the reports'
    required: true
  name:
    description: 'Check run name under which the report is created'
    default: Checkstyle
  title:
    description: 'Check run title under which the report is created'
    default: Checkstyle report
  commit:
    description: 'The commit sha to update the status'
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  changed-since:
    description: >
      This option allow uploading only violations in files that were changed 
      between the current commit and the base commit. Set this parameter to base branch name or commit to 
      skip marking violations on unchanged files. This is especially useful when project code style is changed
      and iterative clean-up is performed.
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: umbrella
  color: purple